# BEGIN_KITTY_OPTIONS
scrollback_lines        10000
remember_window_size    yes
notify_on_cmd_finish    invisible
# END_KITTY_OPTIONS

# BEGIN_KITTY_CURSOR_TRAIL_OPTIONS
cursor_trail                    50
cursor_trail_decay              0.1 0.2
cusror_trail_start_threshold    2
# END_KITTY_CURSOR_TRAIL_OPTIONS

# BEGIN_KITTY_THEME
# Catppuccin Kitty Macchiato
include                 catppuccin-macchiato.conf
macos_titlebar_color    background
# END_KITTY_THEME

# BEGIN_KITTY_FONTS
font_family         family="FiraCode Nerd Font Mono"
bold_font           auto
italic_font         auto
bold_italic_font    auto
# END_KITTY_FONTS
