settings:
  basePath: "~/.config/feo"
  keymap:
    cancel: [escape]
    confirm: [return]
    delete: [d]
    down: [j, down]
    move: [m]
    new: [n]
    scrollDown: ["]"]
    scrollUp: "["
    up: [k, up]
    write: [w]
  theme:
    inactive: orange
    active: cyan
    success: green
    info: blue
    warning: yellow
    error: red
applications:
  feo:
    targets:
      config:
        path: "~/.config/feo/config.yaml"
        sources:
          - path: "~/.config/feo/.config/feo/config.local.yaml"
          - path: "~/.config/feo/.config/feo/config.yaml"
  homebrew:
    targets:
      brewfile:
        path: "~/.Brewfile"
        mediaType: "text/plain"
        sources:
          - path: ".Brewfile"
            mediaType: "text/plain"
  ghostty:
    targets:
      config:
        path: "~/.config/ghostty/config.ghostty"
        mediaType: "text/plain"
        sources:
          - path: ".config/ghostty/config.ghostty"
            mediaType: "text/plain"
  git:
    targets:
      ignore:
        path: "~/.config/git/ignore"
        mediaType: "text/plain"
        sources:
          - path: ".config/git/ignore"
            mediaType: "text/plain"
  hunk:
    targets:
      config:
        path: "~/.config/hunk/config.toml"
        sources:
          - path: ".config/hunk/config.local.toml"
          - path: ".config/hunk/config.toml"
  mise:
    targets:
      config:
        path: "~/.config/mise/config.toml"
        sources:
          - path: ".config/mise/config.toml"
      zshrc:
        mediaType: "text/plain"
        path: "~/.zshrc"
        sources:
          - path: ".zshrc"
            mediaType: "text/plain"
  opencode:
    template:
      vars:
        expertise: TypeScript
    targets:
      config:
        path: "~/.config/opencode/opencode.jsonc"
        sources:
          - path: ".config/opencode/opencode.local.jsonc"
          - path: ".config/opencode/opencode.jsonc"
      agent-plan:
        path: "~/.config/opencode/agents/plan.md"
        sources:
          - path: ".config/opencode/agents/plan.local.yaml"
          - path: ".config/opencode/agents/plan.md"
            template:
              language: liquid
      agent-build:
        path: "~/.config/opencode/agents/build.md"
        sources:
          - path: ".config/opencode/agents/build.local.yaml"
          - path: ".config/opencode/agents/build.md"
            template:
              language: liquid
      agent-review:
        path: "~/.config/opencode/agents/reviewer.md"
        sources:
          - path: ".config/opencode/agents/reviewer.local.yaml"
          - path: ".config/opencode/agents/reviewer.md"
            template:
              language: liquid
      agent-debugger:
        path: "~/.config/opencode/agents/debugger.md"
        sources:
          - path: ".config/opencode/agents/debugger.local.yaml"
          - path: ".config/opencode/agents/debugger.md"
            template:
              language: liquid
      agent-documenter:
        path: "~/.config/opencode/agents/documenter.md"
        sources:
          - path: ".config/opencode/agents/documenter.local.yaml"
          - path: ".config/opencode/agents/documenter.md"
            template:
              language: liquid
      agent-teacher:
        path: "~/.config/opencode/agents/teacher.md"
        sources:
          - path: ".config/opencode/agents/teacher.local.yaml"
          - path: ".config/opencode/agents/teacher.md"
            template:
              language: liquid
      command-debug:
        path: "~/.config/opencode/commands/debug.md"
        sources:
          - path: ".config/opencode/commands/debug.local.yaml"
          - path: ".config/opencode/commands/debug.md"
      command-grill:
        path: "~/.config/opencode/commands/grill.md"
        sources:
          - path: ".config/opencode/commands/grill.local.yaml"
          - path: ".config/opencode/commands/grill.md"
      command-handoff:
        path: "~/.config/opencode/commands/handoff.md"
        sources:
          - path: ".config/opencode/commands/handoff.local.yaml"
          - path: ".config/opencode/commands/handoff.md"
      command-review:
        path: "~/.config/opencode/commands/review.md"
        sources:
          - path: ".config/opencode/commands/review.local.yaml"
          - path: ".config/opencode/commands/review.md"
  starship:
    targets:
      config:
        path: "~/.config/starship.toml"
        sources:
          - path: ".config/starship.local.toml"
          - path: ".config/starship.toml"
  zed:
    targets:
      keymap:
        path: "~/.config/zed/keymap.json"
        mediaType: "text/plain"
        sources:
          - path: ".config/zed/keymap.jsonc"
            mediaType: "text/plain"
      settings:
        path: "~/.config/zed/settings.json"
        sources:
          - path: ".config/zed/settings.local.jsonc"
          - path: ".config/zed/settings.jsonc"
      theme-catppuccin-sky:
        path: "~/.config/zed/themes/catppuccin-sky.json"
        sources:
          - path: ".config/zed/themes/catppuccin-sky.local.json"
          - path: ".config/zed/themes/catppuccin-sky.json"
